For Two Classifiers

Win


Loss

In [1]:
import pandas as pd #importing the pandas package

In [2]:
import numpy as np #importing the numpy package

In [3]:
import matplotlib.pyplot as plt #importing the matplotlib package

In [4]:
import seaborn as sb #importing the seaborn package

In [5]:
%matplotlib inline

In [20]:
data = pd.read_csv("C:\\Users\\tanuj\\Desktop\\Subjects\\DSP\\Project\\nn_output_Win_Loss.csv") #reading the dataset

In [21]:
data.head()

Dealer_count  Hit  Outcome  Player_count  Stand
0            21    1        0            15      0
1            18    0        1            20      1
2            19    1        0             9      0
3            19    1        0            19      0
4            20    1        0            12      0

In [22]:
select_cols = ["Hit","Dealer_count","Player_count"]

In [23]:
x = data[select_cols] #appending the columns to the dataset

In [24]:
y= data.Outcome #Defining our Y variable which is data

In [25]:
from sklearn.model_selection import train_test_split #Importing the train and test function

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=36,stratify=y)

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [28]:
XGB = GradientBoostingClassifier(n_estimators=500,learning_rate=0.01,max_depth=5)

In [29]:
XGB.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=5,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=500,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [30]:
y_pred = XGB.predict(x_test) #Predicting the values on test dataset

In [31]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score #importing the confusion matrix function

In [32]:
cm = confusion_matrix(y_test,y_pred) #calculating the confusion matrix

In [33]:
cm

array([[325,  10],
       [ 27,  52]], dtype=int64)

In [57]:
print(classification_report(y_test,y_pred)) #Printing the classification report

             precision    recall  f1-score   support

          0       0.92      0.97      0.95       335
          1       0.84      0.66      0.74        79

avg / total       0.91      0.91      0.91       414



In [58]:
accuracy_score(y_test,y_pred) #Calculating the accuracy of model

0.91062801932367154

Using Three Classifier 

1) Win

2)Lose

3)Draw

In [37]:
data_new = pd.read_csv("C:\\Users\\tanuj\\Desktop\\Subjects\\DSP\\Project\\nn_output_Win_Loss_Draw.csv") #reading the dataset

In [38]:
data.head()

Dealer_count  Hit  Outcome  Player_count  Stand
0            21    1        0            15      0
1            18    0        1            20      1
2            19    1        0             9      0
3            19    1        0            19      0
4            20    1        0            12      0

In [39]:
select_cols = ["Hit","Dealer_count","Player_count"]

In [40]:
x = data_new[select_cols] #appending the columns to the dataset

In [41]:
y= data_new.Outcome #Defining our Y variable which is data

In [42]:
from sklearn.model_selection import train_test_split #Importing the train and test function

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=36,stratify=y)

In [44]:
from sklearn.ensemble import GradientBoostingClassifier

In [45]:
XGB = GradientBoostingClassifier(n_estimators=500,learning_rate=0.01,max_depth=5)

In [46]:
XGB.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=5,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=500,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [47]:
y_pred = XGB.predict(x_test) #Predicting the values on test dataset

In [48]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score #importing the confusion matrix function

In [49]:
cm = confusion_matrix(y_test,y_pred) #calculating the confusion matrix

In [50]:
print(cm)

[[323  12   0]
 [ 26  52   1]
 [  5   6   0]]


In [51]:
print(classification_report(y_test,y_pred)) #Printing the classification report

             precision    recall  f1-score   support

          0       0.91      0.96      0.94       335
          1       0.74      0.66      0.70        79
          2       0.00      0.00      0.00        11

avg / total       0.86      0.88      0.87       425



In [52]:
accuracy_score(y_test,y_pred) #Calculating the accuracy of model

0.88235294117647056